### ISSUE TITLE
add `Instant -> JSDate`

### ISSUE THREAD

**Issue by coot** [purescript-contrib/purescript-js-date#12]
The purescript-now library provides a way to get `Instant`. The only way to get `JSDate` I can find is through `DateTime`, but this is a long walk ;).  We could solve it either by
* adding an effect in now livbrary to get an js date
* or add a function `Instant -> JSDate`

or both :)

**Comment by chexxor** [comment]
This is really needed. I've struggled to get a JSDate value for the current time several times - it's ridiculously hard problem to solve in PS.

**Comment by garyb** [comment]
Can I ask why you need the `JSDate` for rather than a `Date` / `DateTime`?

It was left out on purpose, because `JSDate` is gross and should be avoided if at all possible. :wink:

**Comment by chexxor** [comment]
I've decided that the browser part of my app is best to use JSDate everywhere, because that app interacts with lots of JS libraries, and they all use JSDate. I need to do simple stuff like pre-fill a datetime-input with the current time, or one a week from now.

A related note: I'd prefer to not ship any `DateTime` libraries to the browser due to my policy. To do that, then, would require adding an FFI function to this library like `foreign import currentJsDate :: Eff _ JSDate`.
